version: "3"
services:
  fileshare-socket:
    image: fileshare-socket
    build:
      target: deploy-socket
    ports:
      - 4001:4001
  fileshare-client:
    image: fileshare-client
    build:
      target: deploy-client
    ports:
      - 4002:80
