version: "3"
services:
  # socket:
  #   build:
  #     context: ./socket
  #     dockerfile: Dockerfile
  #   image: fileshare-socket:local
  #   ports:
  #     - 4001:4001

  # web:
  #   build:
  #     context: ./web
  #     dockerfile: Dockerfile
  #   image: fileshare-web:local
  #   ports:
  #     - 4002:4002

  socket:
    image: fileshare-socket:local
    build:
      target: socket-deploy
    ports:
      - 4001:4001

  web:
    image: fileshare-web:local
    build:
      target: web-deploy
    ports:
      - 4002:4002
