version: "3"
services:
  fileshare-server:
    image: fileshare-server
    build:
      target: deploy-server
    ports:
      - 4001:4001
  fileshare-client:
    image: fileshare-client
    build:
      target: deploy-client
    ports:
      - 4002:80
