version: "3"
services:
  socket:
    image: fileshare-socket
    build:
      target: deploy-socket
    ports:
      - 4001:4001

  web:
    image: fileshare-web
    build:
      target: deploy-web
    ports:
      - 4002:4002
