name: "fileshare"

services:
  fileshare-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: deploy-server
      args:
        - PORT=${PORT:-4001}
    ports:
      - "${PORT:-4001}:${PORT:-4001}"
    environment:
      - PORT=${PORT:-4001}
  fileshare-client:
    image: fileshare-client
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: deploy-client
    ports:
      - 5173:80
